#!/usr/bin/env python3
import os
from sys import argv
from gtkw import write_gtkw

def group(pfx):
    return (pfx, [(pfx)])

traces = [
    "clk_*", "rst_*",
    ("wishbone", ["wb_*"]),
    "*"
]

style = {
    "clk": {"color": "red"},
    "io": {"color": "yellow"},
    "state": {"color": "violet", "base": "dec"}
}

mod = argv[1]
dump = f"tb/{mod}/dump"
write_gtkw(f"{dump}.gtkw", f"{dump}.vcd", traces, style, module=f"TOP.{mod}", clk_period=1.0e-9)
os.execlp("gtkwave", "gtkwave", "-CM6", f"{dump}.gtkw")
